package dxii.betterwithsouls.enums;

public enum EAccBonus {
	GENERIC,
	INVIS,
	DOUBLEJUMP,
	FEATHERFALL,
	RTSR,// +50% ATK DMG IF HP < 20% (2 HEARTS)
	STONERING, //+50% KNOCKBACK
	NOSTEPS, // DRAGONCREST RING, NO STEP SOUNDS
	REDEYE, //ENEMY ATTRACTION
	FOSSILNECKLASE, //+2 FLAT DAMAGE
	STEELRING, // +KNOCKBACK RESISTANCE +20% DAMAGE RESISTANCE
	RUSTRING, //EXTRA WATER MOBILITY
	CLORANTHY, //EXTRA SPEED
	SACRIFICE, //NO ITEM DROP UPON DEATH
	SACRIFICE_BROKEN,
	SACRIFICE_RARE, //SAME AS DEFAAULT ONE, BUT DOESNT BREAK
	CHERRYWOOD, //only every 3th hit spends durability
	FERALBONE, //+100% FOOD HEALING RATE -0.5 heart every 1 minute if not fed for 4 minutes
	HAWKRING, //ARROW DAMAGE +3, ARROW SPEED + 50%
	HORNETRING, //HAWK RING +100% PARRY RIPOSTE DAMAGE
	DODGESCARF, //BOOSTS DODGING
	FROGLEG, //100% HIGHER JUMPING, more blocks to fall to get damage
	DROPRATE, //50% chance to get extra loot
	FIREDEF, //50% FIRE RESISTANCE
	EVILEYE, //bit of health every few kills
}

